//
// Linux_FirewallInterface.mof
//
// © Copyright IBM Corp. 2008
//
// THIS FILE IS PROVIDED UNDER THE TERMS OF THE ECLIPSE PUBLIC LICENSE
// ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
// CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
// 
// You can obtain a current copy of the Eclipse Public License from
// http://www.opensource.org/licenses/eclipse-1.0.php
// 
// Author:  Ashoka Rao S <ashoka.rao@in.ibm.com>
// 
// 

[Description("The class is used to define the ports that are trusted by the firewall")]

class Linux_FirewallInterface : CIM_NetworkPort { 

	[Description("If set - indicates that the Interface is trusted")]
	boolean isTrusted; 

	}; 
